var PT_MAP_CORE = (function() {
function getData(){return(typeof window!=='undefined'&&window.PT_MAP_DATA)?window.PT_MAP_DATA:null;}
var VERSION_RESOURCE_ROOT = '../游戏内容/幻兽帕鲁1.0/资源包/';
var DEFAULT_ICON_LOOKUP = {
    'Alpha Pal': { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_enemy_strong_white.webp', label: '\u5934\u76ee\u5e15\u9c81', icon_width: 30, icon_height: 30 },
    Quest: { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_Icon_Compass_Quest_1.webp', label: '\u4efb\u52a1\u70b9', icon_width: 30, icon_height: 30 },
    'Pal Spawn': { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_11.webp', label: '\u5e15\u9c81\u5237\u65b0', icon_width: 28, icon_height: 28 },
    'Pal Distribution': { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_11.webp', label: '\u5e15\u9c81\u5206\u5e03', icon_width: 24, icon_height: 24 },
    Region: { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_00.webp', label: '\u533a\u57df\u6807\u7b7e', icon_width: 30, icon_height: 30 },
    Bounty: { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_Bounty.webp', label: '通缉犯', icon_width: 30, icon_height: 30 },
    'Fast Travel': { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_FTtower.webp', label: '\u5feb\u901f\u4f20\u9001', icon_width: 40, icon_height: 40 },
    Tower: { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_tower.webp', label: '\u9ad8\u5854', icon_width: 30, icon_height: 30 },
    Ore: { category: 'Mine', fixed_icon: VERSION_RESOURCE_ROOT + '物品图标/T_itemicon_Material_CopperOre.png', label: '\u94dc\u77ff', icon_width: 30, icon_height: 30 },
    Coal: { category: 'Mine', fixed_icon: VERSION_RESOURCE_ROOT + '物品图标/T_itemicon_Material_Coal.png', label: '\u77f3\u70ad', icon_width: 30, icon_height: 30 },
    Sulfur: { category: 'Mine', fixed_icon: VERSION_RESOURCE_ROOT + '物品图标/T_itemicon_Material_Sulfur.png', label: '\u786b\u78fa', icon_width: 30, icon_height: 30 },
    'Pure Quartz': { category: 'Mine', fixed_icon: VERSION_RESOURCE_ROOT + '物品图标/T_itemicon_Material_Quartz.png', label: '\u7eaf\u77f3\u82f1', icon_width: 30, icon_height: 30 },
    'Dungeon Portal': { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_dungeon.webp', label: '\u5730\u4e0b\u57ce\u4f20\u9001\u95e8', icon_width: 30, icon_height: 30 },
    Dungeon: { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_dungeon.webp', label: '\u5730\u4e0b\u57ce', icon_width: 30, icon_height: 30 },
    'Treasure Map': { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_TreasureMap_01.webp', label: '\u85cf\u5b9d\u56fe', icon_width: 30, icon_height: 30 },
    Journals: { category: 'Collectibles', fixed_icon: VERSION_RESOURCE_ROOT + '物品图标/T_itemicon_Consume_TechnologyBook_G3.png', label: '\u65e5\u8bb0/\u7b14\u8bb0', icon_width: 30, icon_height: 30 },
    NPC: { category: 'NPCs', fixed_icon: VERSION_RESOURCE_ROOT + '人物头像/T_CommonHuman_icon_normal.png', label: 'NPC', icon_width: 30, icon_height: 30 },
    'Heat Source': { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '工作图标/T_icon_palwork_00.webp', label: '\u70ed\u6e90', icon_width: 30, icon_height: 30 },
    Incident: { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_Icon_Compass_Quest_1.webp', label: '\u4e8b\u4ef6', icon_width: 30, icon_height: 30 },
    Respawn: { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_07.webp', label: '\u91cd\u751f\u70b9', icon_width: 30, icon_height: 30 },
    Arena: { category: 'Locations', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_11.webp', label: '\u7ade\u6280\u573a', icon_width: 30, icon_height: 30 },
    'Enemy Base': { category: 'Enemies', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_11.webp', label: '\u654c\u65b9\u636e\u70b9', icon_width: 30, icon_height: 30 },
    Treasure: { category: 'Resource', fixed_icon: VERSION_RESOURCE_ROOT + '地图图标/T_icon_compass_02.webp', label: '\u5b9d\u85cf', icon_width: 30, icon_height: 30 }
};
function mergeObjects(base,extra){var out={},k;for(k in base)out[k]=base[k];for(k in (extra||{}))out[k]=extra[k];return out;}
function getIconLookup(){var d=getData();return mergeObjects(DEFAULT_ICON_LOOKUP,(d&&d.iconLookup)?d.iconLookup:{});}
function getMapConfig(){var d=getData();return(d&&d.mapConfig)?d.mapConfig:{};}
var CAT_LABELS={Enemies:'敌人',Resource:'资源',Locations:'地点',Fishing:'钓鱼',Mine:'矿石',NPCs:'NPC',Collectibles:'收集品',Eggs:'帕鲁蛋',Oilrig:'石油平台',Other:'其他'};
function getCategoryLabel(en){return CAT_LABELS[en]||en;}
var DEFAULT_CHECKED=['Alpha Pal','Tower','Fast Travel','Bounty'];
function isDefaultChecked(type){return DEFAULT_CHECKED.indexOf(type)>-1;}
function getCategories(){var lu=getIconLookup();var groups={};Object.keys(lu).forEach(function(type){var m=lu[type]||{},cat=m.category||'Other';if(!groups[cat])groups[cat]=[];groups[cat].push(type);});return groups;}
var PIXEL=131072,MIN_X=-999940,MAX_X=447900,MIN_Y=-737262,MAX_Y=710578,RANGE=1447840,DIVISOR=459,XREF=-582888,YREF=-301000,OFFSET=1000;
function gameToLatLng(x,y){var nx=(x-MIN_X)/RANGE,ny=(y-MIN_Y)/RANGE;return{px:ny*PIXEL,py:(1-nx)*PIXEL};}
function iposToLatLng(ix,iy){var xu=RANGE/DIVISOR,yu=RANGE/DIVISOR,xs=OFFSET+(XREF-MIN_X)/DIVISOR,ys=OFFSET+(YREF-MIN_Y)/DIVISOR;return{px:((ix||0)+ys)/yu*PIXEL,py:(1-(((iy||0)+xs)/xu))*PIXEL};}
function pixelToIpos(px,py){var xu=RANGE/DIVISOR,yu=RANGE/DIVISOR,xs=OFFSET+(XREF-MIN_X)/DIVISOR,ys=OFFSET+(YREF-MIN_Y)/DIVISOR;var x=Number(px),y=Number(py);if(!isFinite(x)||!isFinite(y))return null;return{x:Math.round(x/PIXEL*yu-ys),y:Math.round((1-y/PIXEL)*xu-xs)};}
function rposToIpos(pos){if(!pos)return null;var x=Number(pos.X),y=Number(pos.Y);if(!isFinite(x)||!isFinite(y))return null;var xu=RANGE/DIVISOR,yu=RANGE/DIVISOR,xs=OFFSET+(XREF-MIN_X)/DIVISOR,ys=OFFSET+(YREF-MIN_Y)/DIVISOR,sx=(x-MIN_X)/RANGE,sy=(y-MIN_Y)/RANGE;return{x:Math.round(sy*yu-ys),y:Math.round(sx*xu-xs)};}
function getPointGameCoords(point){if(point&&point.ipos)return{x:Math.round(Number(point.ipos.X)||0),y:Math.round(Number(point.ipos.Y)||0)};if(point&&point.pos)return rposToIpos(point.pos);return null;}
var MAP_META={MainMap:{label:'\u4e3b\u4e16\u754c'},Tree:{label:'\u4e16\u754c\u6811'}};
function getMapList(){var cfg=getMapConfig(),keys=['MainMap','Tree'],list=[];keys.forEach(function(id){if(!cfg[id]&&id!=='MainMap')return;var meta=MAP_META[id]||{};list.push({id:id,label:meta.label||id,image:'',config:cfg[id]||{}});});if(!list.length)list.push({id:'MainMap',label:MAP_META.MainMap.label,image:'',config:{}});return list;}
function getDefaultMapId(){var list=getMapList();return list[0]?list[0].id:'MainMap';}
function getMapById(mapId){var id=mapId||getDefaultMapId(),list=getMapList();for(var i=0;i<list.length;i++){if(list[i].id===id)return list[i];}return list[0]||null;}
function getLandscapeBounds(mapId){var map=getMapById(mapId),cfg=map&&map.config,b=cfg&&cfg.landscapeBounds;if(b&&b.min&&b.max)return b;var old=getMapConfig();if(old&&old.landScapeRealPositionMin&&old.landScapeRealPositionMax)return{min:old.landScapeRealPositionMin,max:old.landScapeRealPositionMax};return{min:{X:MIN_X,Y:MIN_Y},max:{X:MAX_X,Y:MAX_Y}};}
function isPointInsideMap(point,mapId){var pos=point&&point.pos;if(!pos)return false;var b=getLandscapeBounds(mapId),x=Number(pos.X),y=Number(pos.Y);if(!isFinite(x)||!isFinite(y))return false;return x>=Number(b.min.X)&&x<=Number(b.max.X)&&y>=Number(b.min.Y)&&y<=Number(b.max.Y);}
function getPointMapId(point){if(point&&point.mapId)return point.mapId;if(isPointInsideMap(point,'Tree'))return'Tree';return'MainMap';}
function posToMapPixel(pos,mapId){if(!pos)return null;var b=getLandscapeBounds(mapId),x=Number(pos.X),y=Number(pos.Y),minX=Number(b.min.X),maxX=Number(b.max.X),minY=Number(b.min.Y),maxY=Number(b.max.Y);if(!isFinite(x)||!isFinite(y)||!isFinite(minX)||!isFinite(maxX)||!isFinite(minY)||!isFinite(maxY)||maxX===minX||maxY===minY)return null;return{px:(y-minY)/(maxY-minY)*PIXEL,py:(1-(x-minX)/(maxX-minX))*PIXEL};}
function getPointPixelCoords(point,mapId){if(!point)return null;var id=mapId||getPointMapId(point);if(point.pos){var byPos=posToMapPixel(point.pos,id);if(byPos)return byPos;}if(point.ipos){var ix=Number(point.ipos.X),iy=Number(point.ipos.Y);if(isFinite(ix)&&isFinite(iy)){if(ix>=0&&ix<=PIXEL&&iy>=0&&iy<=PIXEL)return{px:ix,py:iy};return iposToLatLng(ix,iy);}}return null;}
function pushPoint(list,source,type,item,index){if(!source)return;var point={type:type,item:item||source.item||source.name||source.id||source.characterID||type,pos:source.pos,ipos:source.ipos,mapId:source.mapId,source:index};if(point.pos||point.ipos)list.push(point);}
function pushLP(list,item,index){if(!item)return;var point={type:item.type||'Unknown',item:item.item||item.type||'Unknown',pos:item.pos,ipos:item.ipos,mapId:item.mapId,source:index,id:item.id||''};if(point.pos||point.ipos)list.push(point);}
function buildPointsFromFact(d){var list=[];(d.bossSpawns||[]).forEach(function(item,index){if(item.characterID==='None'){pushPoint(list,item,'Bounty','通缉犯',index);}else{pushPoint(list,item,'Alpha Pal',item.characterID||item.id,index);}});(d.questLocations||[]).forEach(function(item,index){pushPoint(list,item,'Quest',item.id,index);});var sp=d.spawnerPlacements||{};(sp.linked||[]).forEach(function(item,index){pushPoint(list,item,'Pal Spawn',item.spawnerName||item.spawnerType,index);});(sp.unlinked||[]).forEach(function(item,index){pushPoint(list,item,'Pal Spawn',item.spawnerName||item.spawnerType,index);});return list;}
function getAllPoints(){var d=getData();if(!d)return[];if(d.points)return d.points;var list=buildPointsFromFact(d);(d.pointsFromLevel||[]).forEach(function(item,index){pushLP(list,item,index);});return list;}
function getPointsForMap(mapId){var id=mapId||getDefaultMapId();return getAllPoints().filter(function(point){return getPointMapId(point)===id;});}
function getClusterStage(progress,breaks){var list=breaks||[0,0.2,0.4,0.6];var value=Number(progress);if(!isFinite(value))value=0;value=Math.round(value*1000000000)/1000000000;for(var i=list.length-1;i>=0;i--){if(value>=list[i])return i;}return 0;}
function getStageZoom(stage,minZoom,maxZoom,breaks){var list=breaks||[0,0.2,0.4,0.6];var min=Number(minZoom),max=Number(maxZoom),index=Math.max(0,Math.min(list.length-1,Number(stage)||0));if(!isFinite(min)||!isFinite(max)||max<=min)return max;return min+(max-min)*(list[index]||0);}
function getStageScale(stage,minZoom,maxZoom,nativeZoom,breaks){var zoom=getStageZoom(stage,minZoom,maxZoom,breaks);var native=Number(nativeZoom);if(!isFinite(native))native=8;return Math.pow(2,zoom-native);}
var CLUSTER_PROFILE_RADII={never:[0,0,0,0],light:[120,0,0,1],normal:[260,64,0,1],heavy:[420,220,84,1]};
var CLUSTER_TYPE_PROFILES={'Region':'never','Fast Travel':'never','Tower':'never','Alpha Pal':'never','Rampaging':'never','Bounty':'never','Home':'never','Dungeon':'light','Dungeon Portal':'light','Cave Entrance':'light','Journals':'light','Treasure Map':'light','Treasure Element':'light','Black Marketeer':'light','Wandering Merchant':'light','Arrogant Pal Critic':'light','Fishing Spot':'light','NPC':'light','Heat Source':'never','Arena':'never','Respawn':'never','Treasure':'normal','Lifmunk Effigy':'normal','Supply':'normal','Crude Oil':'normal','Sulfur':'normal','Pure Quartz':'normal','Coal':'normal','Beautiful Flower':'normal','Kinship Peach':'normal','Anti-Air Turret':'normal','Enemy Base':'normal','Incident':'normal','Ore':'heavy','Salvage Rank1':'heavy','Salvage Rank2':'heavy','Hexolite Quartz':'heavy','Chromite':'heavy','Desert Egg':'heavy','Feybreak Egg':'heavy','Frozen Egg':'heavy','Grass Egg':'heavy','Sakura Egg':'heavy','Volcano Egg':'heavy','Junk':'heavy','Oilrig Treasure':'heavy','Oilrig Treasure Goal':'heavy'};
function getClusterProfile(type){return CLUSTER_TYPE_PROFILES[type]||'normal';}
function getClusterStageRadii(type){var profile=getClusterProfile(type);return(CLUSTER_PROFILE_RADII[profile]||CLUSTER_PROFILE_RADII.normal).slice();}
function shouldClusterMapType(type,category){return getClusterProfile(type)!=='never';}
function shouldUpdateMapTypeOnZoomStage(type,category,clusterEnabled){return clusterEnabled===true&&shouldClusterMapType(type,category);}
function createClusterFromPoint(point){return{px:Number(point.px)||0,py:Number(point.py)||0,count:1,points:[point]};}
function addPointToCluster(cluster,point){cluster.points.push(point);cluster.count=cluster.points.length;var count=cluster.count;var px=Number(point.px)||0,py=Number(point.py)||0;cluster.px+=(px-cluster.px)/count;cluster.py+=(py-cluster.py)/count;}
function getClusterGridCoord(value,cellSize){return Math.floor(value/cellSize);}
function getClusterGridKey(x,y){return x+':'+y;}
function addClusterToGrid(grid,cells,index,x,y){var key=getClusterGridKey(x,y);if(!grid[key])grid[key]=[];grid[key].push(index);cells[index]={x:x,y:y,key:key};}
function removeClusterFromGrid(grid,cells,index){var cell=cells[index];if(!cell)return;var bucket=grid[cell.key];if(!bucket)return;var position=bucket.indexOf(index);if(position!==-1)bucket.splice(position,1);if(bucket.length===0)delete grid[cell.key];}
function moveClusterInGrid(grid,cells,index,cluster,cellSize){var x=getClusterGridCoord(cluster.px,cellSize),y=getClusterGridCoord(cluster.py,cellSize);var current=cells[index];if(current&&current.x===x&&current.y===y)return;removeClusterFromGrid(grid,cells,index);addClusterToGrid(grid,cells,index,x,y);}
function findLinearClusterIndex(clusters,px,py,radiusSquared){for(var i=0;i<clusters.length;i++){var dx=px-clusters[i].px,dy=py-clusters[i].py;if(dx*dx+dy*dy<=radiusSquared)return i;}return-1;}
function findGridClusterIndex(grid,clusters,x,y,px,py,radiusSquared){var matchIndex=-1;for(var offsetY=-1;offsetY<=1;offsetY++){for(var offsetX=-1;offsetX<=1;offsetX++){var bucket=grid[getClusterGridKey(x+offsetX,y+offsetY)];if(!bucket)continue;for(var i=0;i<bucket.length;i++){var candidateIndex=bucket[i];if(matchIndex!==-1&&candidateIndex>=matchIndex)continue;var candidate=clusters[candidateIndex];var dx=px-candidate.px,dy=py-candidate.py;if(dx*dx+dy*dy<=radiusSquared)matchIndex=candidateIndex;}}}return matchIndex;}
function buildSpatialStageClusters(points,options){var opts=options||{};var list=opts.stageRadii||[260,140,52,1];var stage=Math.max(0,Math.min(list.length-1,Number(opts.stage)||0));var radius=Number(list[stage]);if(!isFinite(radius)||radius<1)radius=1;var scale=getStageScale(stage,opts.minZoom,opts.maxZoom,opts.nativeZoom,opts.stageBreaks);var scaledRadius=radius/(!isFinite(scale)||scale<=0?1:scale);var radiusSquared=scaledRadius*scaledRadius;var grid={},cells=[],clusters=[];for(var i=0;i<(points||[]).length;i++){var point=points[i];var px=Number(point&&point.px),py=Number(point&&point.py);if(!isFinite(px)||!isFinite(py))continue;var gridX=getClusterGridCoord(px,scaledRadius),gridY=getClusterGridCoord(py,scaledRadius);var matchIndex=clusters.length<64?findLinearClusterIndex(clusters,px,py,radiusSquared):findGridClusterIndex(grid,clusters,gridX,gridY,px,py,radiusSquared);if(matchIndex!==-1){addPointToCluster(clusters[matchIndex],point);moveClusterInGrid(grid,cells,matchIndex,clusters[matchIndex],scaledRadius);}else{var cluster=createClusterFromPoint(point),index=clusters.length;clusters.push(cluster);addClusterToGrid(grid,cells,index,gridX,gridY);}}return clusters;}
function buildStageClusters(points,options){return buildSpatialStageClusters(points,options);}
function getClusterAnimationOrigin(keys,origins){var totalX=0,totalY=0,count=0;for(var i=0;i<(keys||[]).length;i++){var origin=origins&&origins[keys[i]];if(!origin)continue;var x=Number(origin.x),y=Number(origin.y);if(!isFinite(x)||!isFinite(y))continue;totalX+=x;totalY+=y;count++;}return count?{x:totalX/count,y:totalY/count}:null;}
function getSortedKeySet(keys){return(keys||[]).slice().sort().join('|');}
function shouldAnimateClusterExit(keys,origin,targets){if(!keys||!keys.length||!origin||!targets)return false;var oldSet=getSortedKeySet(keys),match=null,targetSet='';for(var i=0;i<keys.length;i++){var target=targets[keys[i]],currentSet=target&&getSortedKeySet(target.keys);if(!target||!currentSet||(targetSet&&currentSet!==targetSet))return false;if(!match){match=target;targetSet=currentSet;}}if((match.keys||[]).length>keys.length)return true;if(targetSet!==oldSet)return false;var ox=Number(origin.x),oy=Number(origin.y),tx=Number(match.x),ty=Number(match.y);if(!isFinite(ox)||!isFinite(oy)||!isFinite(tx)||!isFinite(ty))return false;return Math.abs(ox-tx)>=1||Math.abs(oy-ty)>=1;}
function shouldAnimateClusterEntry(keys,origins){if(!keys||!keys.length||!origins)return false;var originSet='';for(var i=0;i<keys.length;i++){var origin=origins[keys[i]],currentSet=origin&&getSortedKeySet(origin.keys);if(!origin||!currentSet||(originSet&&currentSet!==originSet))return false;originSet=currentSet;}return(origins[keys[0]].keys||[]).length>keys.length;}
function getClusterMergeExitFrames(startX,startY,endX,endY){var sx=Math.round(Number(startX)||0),sy=Math.round(Number(startY)||0),ex=Math.round(Number(endX)||0),ey=Math.round(Number(endY)||0);function frame(offset,scale,opacity){var x=Math.round(sx+(ex-sx)*offset),y=Math.round(sy+(ey-sy)*offset);return{transform:'translate3d('+x+'px,'+y+'px,0) scale('+scale+')',opacity:opacity,offset:offset};}return[frame(0,1,1),frame(0.45,0.96,1),frame(0.82,0.78,0.25),frame(1,0.72,0)];}
function isRegionLabelType(type){return type==='Region';}
function getRegionLabelFontSize(progress){var value=Number(progress);if(!isFinite(value))value=0;value=Math.max(0,Math.min(1,value));return Math.round(10+(18-10)*value);}
function getRegionLabelZIndexOffset(){return 10000;}
function getZoomClusterUpdateFrameDelay(){return 2;}
function getLeafletMapAnimationOptions(){return{zoomAnimation:true,fadeAnimation:false,markerZoomAnimation:true};}
function getLeafletTileAnimationOptions(){return{updateWhenZooming:true,updateWhenIdle:false,keepBuffer:6};}
function getTilePreloadOptions(){return{maxNativeZoom:4,panBuffer:2,zoomProgressThreshold:0.55};}
return{getData:getData,getIconLookup:getIconLookup,getMapConfig:getMapConfig,getMapList:getMapList,getDefaultMapId:getDefaultMapId,getMapById:getMapById,getPointMapId:getPointMapId,getPointPixelCoords:getPointPixelCoords,getPointsForMap:getPointsForMap,getCategoryLabel:getCategoryLabel,isDefaultChecked:isDefaultChecked,getCategories:getCategories,gameToLatLng:gameToLatLng,iposToLatLng:iposToLatLng,pixelToIpos:pixelToIpos,rposToIpos:rposToIpos,getPointGameCoords:getPointGameCoords,getAllPoints:getAllPoints,getClusterStage:getClusterStage,getClusterProfile:getClusterProfile,getClusterStageRadii:getClusterStageRadii,shouldClusterMapType:shouldClusterMapType,shouldUpdateMapTypeOnZoomStage:shouldUpdateMapTypeOnZoomStage,buildStageClusters:buildStageClusters,getClusterAnimationOrigin:getClusterAnimationOrigin,shouldAnimateClusterExit:shouldAnimateClusterExit,shouldAnimateClusterEntry:shouldAnimateClusterEntry,getClusterMergeExitFrames:getClusterMergeExitFrames,isRegionLabelType:isRegionLabelType,getRegionLabelFontSize:getRegionLabelFontSize,getRegionLabelZIndexOffset:getRegionLabelZIndexOffset,getZoomClusterUpdateFrameDelay:getZoomClusterUpdateFrameDelay,getLeafletMapAnimationOptions:getLeafletMapAnimationOptions,getLeafletTileAnimationOptions:getLeafletTileAnimationOptions,getTilePreloadOptions:getTilePreloadOptions};
})();if(typeof window!=='undefined')window.PT_MAP_CORE=PT_MAP_CORE;if(typeof module!=='undefined'&&module.exports)module.exports=PT_MAP_CORE;
