const assert = require('assert');
const fs = require('fs');
const path = require('path');

const source = fs.readFileSync(path.join(__dirname, '技能网页.js'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '..', '样式', '技能网页样式.css'), 'utf8');
assert.ok(source.includes('.catalog'), '伙伴技能页必须读取生成目录');
assert.ok(!source.includes('partnerData = (results[0] && results[0].partnerSkills)'), '伙伴技能页不应再直接遍历图鉴全量事实');
assert.ok(source.includes('partnerCatalogIds.slice()'), '伙伴技能页应保留生成目录的六大分类和泰拉瑞亚末尾顺序');
assert.ok(source.includes("var PARTNER_CATEGORIES = ['普通帕鲁', '石板Boss', '塔主Boss', 'Boss', '狂暴化', '其他'];"), '伙伴技能页应该定义六个并列分类');
assert.ok(source.includes('data-sk-partner-category'), '伙伴技能页应该渲染可点击的分类按钮');
assert.ok(source.includes('filterPartnerSkills'), '伙伴技能页必须复用核心层筛选，不能复制分类逻辑');
assert.ok(source.includes("closest('[data-sk-partner-category]')"), '伙伴技能页应该响应六项分类按钮');
assert.ok(source.includes('data-sk-partner-filter-group'), '伙伴技能页应该把九个用途大类显示为固定侧栏分组');
assert.ok(source.includes('data-sk-partner-facet-option'), '固定侧栏必须直接提供所有筛面选项');
assert.ok(source.includes('data-sk-partner-filter-search'), '固定侧栏必须能搜索几十个筛选项');
assert.ok(source.includes('data-sk-partner-remove-filter'), '已选条件必须能够逐项移除');
assert.ok(source.includes('data-sk-partner-clear-filters'), '已选条件必须能够一键清空');
assert.ok(source.includes('partnerFacetSelections'), '快速浏览与组合查询必须共用一份分面选择状态');
assert.ok(source.includes('facetSelections: partnerFacetSelections'), '页面必须把按筛面分组的选择交给核心层');
assert.ok(source.includes('getPartnerFacetCounts'), '每个筛选项必须显示当前其他条件下的动态数量');
assert.ok(source.includes('getPartnerSelectedFilters'), '顶部已选条件必须独立于筛选项搜索结果');
assert.ok(source.includes('sk-partner-filter-summary'), '结果区必须用自然语言说明所有选择都按“且”生效');
assert.ok(source.includes('所选条件必须全部满足'), '筛选说明必须明确同一行和跨行都是交集');
assert.ok(!source.includes('同项为“或”'), '筛选栏不能再残留同一行按“或”的错误提示');
assert.ok(!source.includes('data-sk-partner-advanced'), '页面不得保留独立的组合筛选入口');
assert.ok(!source.includes('requiredCapabilityIds'), '页面不得保留旧的全条件“且”筛选参数');
assert.ok(!source.includes('partnerUsageSubcategory'), '页面不得保留只展开当前大类的三级单选状态');
assert.ok(source.includes('sk-partner-avatar'), '伙伴技能卡片必须显示帕鲁头像');
assert.ok(source.indexOf('sk-partner-pal-name') < source.indexOf('sk-partner-skill-name'), '卡片源码必须先放帕鲁名，再放伙伴技能名');
assert.ok(source.includes('renderPartnerRankTable'), '伙伴技能页必须使用共用等级表');
assert.ok(source.includes('renderPartnerFixedParameters'), '伙伴技能页必须显示主动伙伴技能的固定冷却和持续时间');
assert.ok(!source.includes("var trigger = p.trigger"), '伙伴技能卡片不应显示没有筛选价值的“玩家使用”标签');
assert.ok(!source.includes('sk-partner-star'), '伙伴技能卡片不应继续使用遗漏参数的单列星级值');
assert.ok(/\.sk-partner-avatar\{[^}]*width:48px[^}]*height:48px/.test(css), '伙伴技能头像必须使用稳定的 48px 尺寸');
assert.ok(/\.sk-partner-browser\{[^}]*display:grid/.test(css), '伙伴技能页必须使用固定侧栏与结果区双栏布局');
assert.ok(/\.sk-partner-filter-sidebar\{[^}]*overflow-y:auto/.test(css), '筛选项很多时只能在固定侧栏内部滚动');
assert.ok(/\.sk-partner-filter-group\{[^}]*border/.test(css), '每个用途大类必须有清楚的折叠分组边界');
assert.ok(/\.sk-partner-applied\{[^}]*display:flex/.test(css), '结果区上方必须持续展示已选条件');
assert.ok(/@media \(max-width:900px\)[^{]*\{[^}]*\.sk-partner-browser\{[^}]*grid-template-columns:1fr/.test(css), '窄屏必须退化为单列布局');
assert.ok(!css.includes('!important'), '伙伴技能样式不能靠 !important 覆盖旧实现');

console.log('伙伴技能目录读取测试通过');
